config/routes.rb
TheRightBrain::Application.routes.draw do
  resources :clients
  resources :pages
  resources :logins
  
  root :to => 'pages#home'
  
  get '/resume' => 'pages#resume'
  get '/client' => 'clients#show', as: :client
  get "client/:id" => "clients#show"
  get "clients"=> "clients#new"
  get "photos" => "pages#photos"
  get "discography" => "pages#discography"
  get "commercial_music" => "pages#commercial"
  get "bridal_music" => "pages#bridal"
  get "art" => "pages#art"
  get "contact" => "pages#contact"
  post "contact" => "pages#create"
  get "violins" => "pages#violins"
  get "press" => "pages#press"
  get "videos" => "pages#videos"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address, :email, :date, :location, :name, :Time, :Venu_Adress,:password, :password_confirmation, :payment, :phone, :songs
  has_secure_password
  validates_presence_of :password, :on => :create
end

app/models/page.rb
class Page < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    if @client.id == session[:user_id] 
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @client }
      end
    else
       redirect_to(root_path)
     end
     
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to root_url, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
  end
  
  def create
    @client = Client.find_by_email(params[:email])
    
    if @client && @client.authenticate(params[:password])
      session[:user_id] =  @client.id
      session[:username] = @client.name
      redirect_to("/clients/#{@client.id}")
    else
      redirect_to("/logins/new?invalid_password=true&email=#{params[:email]}")
    end
  end
  
  def index
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(:root)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages

  # GET /pages.json
  def index
    @pages = Page.all
    @client = Client.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end
  
  def photos
  end
  def discography
  end
  def commercial
  end
  def art
  end
  def violins
  end
  def videos
  end
  
  def contact

  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    fname = params[:fname]
    email = params[:email]
    mess = params[:description]
    ContactForm.contact_email(fname, email, mess).deliver
    redirect_to :root

    
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_contact.html.erb
<div id = "contact" class="bottom_nav row">
  <div class="large-6 columns">
    <h1 class="bottom_nav_h1 bottom_header">CLIENT LOG IN</h1>
    <p class="subheader sub2">check in <p>
  </div>
  <div class="large-6 columns">
    <h1 class="bottom_nav_h1 bottom_header">CONTACT </p>
    <p class="subheader">say hello <p>
    <form name="contact" action="/contact" method="post" class="contact_form">    
        <p><%= text_field_tag 'fname', nil, placeholder: 'NAME',:class => "inputtimes" %> </p>
        <p><%= text_area_tag 'description',nil, placeholder: 'MESSAGE',:class => "text-fieldtimes"%></p>
        <p><%= email_field_tag 'email', nil, placeholder: 'EMAIL',:class => "inputtimes" %></p>
      <input type="submit" value="SEND" class="submit_button">  
    </form>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name ,:class => 'form_input'%>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email,:class => 'form_input'%>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation ,:class => 'form_input'%>
  </div>
  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone ,:class => 'form_input'%>
  </div>
  
  
  
  
  <h1>EVENT</h1>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :Time %><br />
    <%= f.text_field :Time ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :Venu_Adress %><br />
    <%= f.text_field :Venu_Adress ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :songs %><br />
    <%= f.text_field :songs ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :payment %><br />
    <%= f.text_field :payment ,:class => 'form_input' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/_mobilenav.html.erb
<div class="hide-for-medium-up mobilenav_bar">        
        <button type="button" id="trigger-overlay" role="button" aria-label="Toggle Navigation" id="mbtn" class="toggle lines-button x">
          <span class="lines"></span>
        </button>
</div>


<div class="overlay show-for-small-only">
  <div class="mobiletext">
  					<p class="overlay_p">
              <a href="#about_section">About</a>
            </p>
  					<p id="mobile_music" class="overlay_p2"><a href="#">Music</a></p>
            <div id="mobile_music_subnav">
                <div class="small-3 large-3 columns">
                  <a href="/#solomusic">solo</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="/commercial_music">Film</a>
                  </div>
                <div class="small-3 large-3 columns">
                  <a href="/discography">other</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="bridal_music">bridal</a>
                  </div>
            </div>
            <p class="overlay_p2"><a href="#">Violins</a></p>
  					<p id="mobile_media" class="overlay_p2"><a href="#">Media</a></p>
            <div id="mobile_media_subnav">
                <div class="small-4 large-4 columns">
                  <a href="/videos">video</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/photos">photo</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/press">press</a>
                  </div>

            </div>
  					<p class="overlay_p2"><a href="/art">Art</a></p>
  					<p class="overlay_p2"><a href="/#contact">Contact</a></p> 
    </div>
</div>

app/views/clients/_nav.html.erb
<div class="navbg stay show-for-medium-up">  
  <div class="row main_navigation">
    <div class="small-2 large-2 columns">
      <a id = "about" href="/#about_section">About</a>
    </div>
    <div class="small-2 large-2 columns">
      <a id = "music" href="#solo_music">Music</a>
    </div>
    <div class="small-2 large-2 columns">
      <a href="/violins"> Violins</a>
    </div>
    <div id = "media" class="small-2 large-2 columns">
      Media
    </div>
    <div class="small-2 large-2 columns">
      <a href="/art">Art</a>
    </div>
    <div class="small-2 large-2 columns">
      <a href="#contact"> Contact </a>
    </div>
  </div>
  <div id="music_submenu">
    <div>
      <div class="small-3 large-3 columns">
        <a href="/#solo_music">solo</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/commercial_music">commercial</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/discography">discography</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/bridal_music">bridal</a>
      </div>
    </div>
  </div>
  <div id="media_submenu">
    <div>
      <div class="small-4 large-4 columns">
        <a href="/videos">video</a>
      </div>
      <div class="small-4 large-4 columns">
        <a href="/photos">photo</a>
      </div>
      <div class="small-4 large-4 columns">
        <a href="/press">press</a>
      </div>
    </div>
  </div>
</div>
<img src="/assets/triangle.png" id="that_triangle" class="show-for-medium-up">

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Date</th>
    <th>Location</th>
    <th>Songs</th>
    <th>Payment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.address %></td>
    <td><%= client.phone %></td>
    <td><%= client.date %></td>
    <td><%= client.location %></td>
    <td><%= client.songs %></td>
    <td><%= client.payment %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<div class="new_client_page">
<h1>New client</h1>

<div class="new_form">
  <%= render 'form' %>
</div>

<%= link_to 'Back', clients_path %>
</div>

app/views/clients/show.html.erb
<div class="show_page row">
  <p id="notice"><%= notice %></p>

<h1 class="client">CLIENT INFORMATION</h1>
<hr>
  <p>
    <b>Name:</b>
    <%= @client.name %>
  </p>

  <p>
    <b>Email:</b>
    <%= @client.email %>
  </p>

  <p>
    <b>Address:</b>
    <%= @client.address %>
  </p>

  <p>
    <b>Phone:</b>
    <%= @client.phone %>
  </p>

  <h1 class="client">EVENT</h1>
<hr>
  <p>
    <b>Date:</b>
    <%= @client.date %>
  </p>
  <p>
    <b>Time:</b>
    <%= @client.Time %>
  </p>

  <p>
    <b>Location:</b>
    <%= @client.location %>
    <%= @client.Venu_Adress %>
  </p>

  <p>
    <b>Songs:</b>
    <%= @client.songs %>
  </p>

  <p>
    <b>Payment:</b>
    <%= @client.payment %>
  </p>
  
  <p>
    <% link_to 'Edit', edit_client_path(@client) %> 
    <%  link_to 'Back', clients_path %>
  </p>

</div>

app/views/contact_form/contact_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1><%= "#{@fname}, #{@email}"%></h1>
    <p>
      <%= @mess %>
    </p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRightBrain</title>
  <%= javascript_include_tag :jquery %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
  <meta property="og:image" content="/assets/photos/21.jpg"/>
  <meta property="og:title" content="KAITLYN HOVA"/>
  <meta property="og:url" content="www.KaitlynHova.com"/>
  <meta name="twitter:title" content="KAITLYN HOVA">
  
  <link rel="icon" type="image/png" href="/assets/favicon.png">

  <script type="text/javascript" src="//use.typekit.net/xty1bvd.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag "component" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag :masonry %>
  <%= javascript_include_tag :modernizr %>
  <%= javascript_include_tag :fancybox %>
  <%= javascript_include_tag :fancyboxmedia %>


  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="//use.typekit.net/xty1bvd.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  
  <%= csrf_meta_tags %>
  <%= render 'nav' %>
  <%= render 'mobilenav' %>
  
  
</head>
<body>

<%= yield %>
  <%= render 'contact' %>
</body>

</html>

app/views/logins/_contact.html.erb
<div id = "contact" class="bottom_nav row">
  <div class="large-6 columns">
    <h1 class="bottom_nav_h1 bottom_header">CLIENT LOG IN</h1>
    <p class="subheader sub2">check in <p>
  </div>
  <div class="large-6 columns">
    <h1 class="bottom_nav_h1 bottom_header">CONTACT </p>
    <p class="subheader">say hello <p>
    <form name="contact" action="/contact" method="post" class="contact_form">    
        <p><%= text_field_tag 'fname', nil, placeholder: 'NAME',:class => "inputtimes" %> </p>
        <p><%= text_area_tag 'description',nil, placeholder: 'MESSAGE',:class => "text-fieldtimes"%></p>
        <p><%= email_field_tag 'email', nil, placeholder: 'EMAIL',:class => "inputtimes" %></p>
      <input type="submit" value="SEND" class="submit_button">  
    </form>
  </div>
</div>

app/views/logins/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name ,:class => 'form_input'%>
  </div>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation ,:class => 'form_input'%>
  </div>
  
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :songs %><br />
    <%= f.text_field :songs ,:class => 'form_input'%>
  </div>
  <div class="field">
    <%= f.label :payment %><br />
    <%= f.text_field :payment ,:class => 'form_input' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/_mobilenav.html.erb
<div class="hide-for-medium-up mobilenav_bar">        
        <button type="button" id="trigger-overlay" role="button" aria-label="Toggle Navigation" id="mbtn" class="toggle lines-button x">
          <span class="lines"></span>
        </button>
</div>


<div class="overlay show-for-small-only">
  					<p class="overlay_p">
              <a href="#about_section">About</a>
            </p>
  					<p id="mobile_music" class="overlay_p2"><a href="#">Music</a></p>
            <div id="mobile_music_subnav">
                <div class="small-3 large-3 columns">
                  <a href="/#solomusic">solo</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="/commercial_music">Film</a>
                  </div>
                <div class="small-3 large-3 columns">
                  <a href="/discography">other</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="bridal_music">bridal</a>
                  </div>
            </div>
            <p class="overlay_p2"><a href="#">Violins</a></p>
  					<p id="mobile_media" class="overlay_p2"><a href="#">Media</a></p>
            <div id="mobile_media_subnav">
                <div class="small-4 large-4 columns">
                  <a href="/videos">video</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/photos">photo</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/press">press</a>
                  </div>

            </div>
  					<p class="overlay_p2"><a href="#">Art</a></p>
  					<p class="overlay_p2"><a href="/#contact">Contact</a></p> 
</div>

app/views/logins/_nav.html.erb
<div class="navbg stay show-for-medium-up">  
  <div class="row main_navigation">
    <div class="small-2 large-2 columns">
      <a id = "about" href="/#about_section">About</a>
    </div>
    <div class="small-2 large-2 columns">
      <a id = "music" href="#solo_music">Music</a>
    </div>
    <div class="small-2 large-2 columns">
      <a href="/violins"> Violins</a>
    </div>
    <div id = "media" class="small-2 large-2 columns">
      Media
    </div>
    <div class="small-2 large-2 columns">
      <a href="/art">Art</a>
    </div>
    <div class="small-2 large-2 columns">
      <a href="#contact"> Contact </a>
    </div>
  </div>
  <div id="music_submenu">
    <div>
      <div class="small-3 large-3 columns">
        <a href="/#solo_music">solo</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/commercial_music">commercial</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/discography">discography</a>
      </div>
      <div class="small-3 large-3 columns">
        <a href="/bridal_music">bridal</a>
      </div>
    </div>
  </div>
  <div id="media_submenu">
    <div>
      <div class="small-4 large-4 columns">
        <a href="/videos">video</a>
      </div>
      <div class="small-4 large-4 columns">
        <a href="/photos">photo</a>
      </div>
      <div class="small-4 large-4 columns">
        <a href="/press">press</a>
      </div>
    </div>
  </div>
</div>
<img src="assets/triangle.png" id="that_triangle" class="show-for-medium-up">

app/views/logins/new.html.erb
<% if params[:invalid_password] == "true" %>
  <p>Invalid password for name <%= params[:name] %></p>
<% end %>

<h1>Log In</h1>

<div style="position:relative; z-index: 2000;">
<%= form_tag logins_path do %>

  <%= label_tag :email %>
  <%= text_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>
  
  <%= submit_tag "Log In" %>
<% end %>
</div>

app/views/pages/_commercial.html.erb
<div id="solo_music">	
    <h1> MUSIC</h1>
    <h3> commercial </h3>
    
    <div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">

			</div>
			<section class="grid3d vertical" id="grid3d">
				<div class="grid-wrap" style="-webkit-perspective-origin-y: 0px !important;">
					<div class="grid">
						<figure><img src="assets/discography/khlogo.gif" alt="img01"/></figure>
            <figure><img src="assets/discography/simplemobile.gif" alt="img04"/></figure>
						<figure><img src="assets/discography/khlogo.gif" alt="img08"/></figure>
						<figure><img src="assets/discography/jacuzzi.gif" alt="img02"/></figure>
            <figure><img src="assets/discography/khlogo.gif" alt="img05"/></figure>
					</div>
				</div><!-- /grid-wrap -->
				<div class="content">
					<div>
						<iframe width="100%" height="450" style="max-width:600px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/63554074&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
						<p class="dummy-text dummy-title">Vestin Commercial Mix</p>
					</div>
					<div>
						<iframe width="512" height="288" style="max-width:600px" src="http://www.poptent.com/getplayer/56486?" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
						<p class="dummy-text dummy-title">Simple Mobile</p>
					</div>
					<div>
						<iframe width="100%" height="450"  style="max-width:600px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/62745053&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
						<p class="dummy-text dummy-title">Film Score Clip</p>
					</div>
					<div>
						<iframe width="512" height="288" style="max-width:600px" src="http://www.poptent.com/getplayer/49751?" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
            <p class="dummy-text dummy-title">Jacuzzi Commercial Mix</p>
					</div>
					<div>
						<iframe width="100%" height="450" style="max-width:600px" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/62745323&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
						<p class="dummy-text dummy-title">Janky Theme</p>
					</div>
					<span class="loading"></span>
					<span class="icon close-content"></span>
				</div>
			</section>
			<section>
			</section>

		</div><!-- /container -->
		<script>
			new grid3D( document.getElementById( 'grid3d' ) );
		</script>
</div>

app/views/pages/_mobilenav.html.erb
<div class="hide-for-medium-up mobilenav_bar">        
        <button type="button" id="trigger-overlay" role="button" aria-label="Toggle Navigation" id="mbtn" class="toggle lines-button x">
          <span class="lines"></span>
        </button>
</div>


<div class="overlay show-for-small-only">
  <div class="mobiletext">
  					<p class="overlay_p">
              <a href="#about_section">About</a>
            </p>
  					<p id="mobile_music" class="overlay_p2"><a href="#">Music</a></p>
            <div id="mobile_music_subnav">
                <div class="small-3 large-3 columns">
                  <a href="/#solomusic">solo</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="/commercial_music">film</a>
                  </div>
                <div class="small-3 large-3 columns">
                  <a href="/discography">other</a>
                </div>
                <div class="small-3 large-3 columns">
                  <a href="bridal_music">bridal</a>
                  </div>
            </div>
            <p class="overlay_p2"><a href="#">Violins</a></p>
  					<p id="mobile_media" class="overlay_p2"><a href="#">Media</a></p>
            <div id="mobile_media_subnav">
                <div class="small-4 large-4 columns">
                  <a href="/videos">video</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/photos">photo</a>
                  </div>
                <div class="small-4 large-4 columns">
                  <a href="/press">press</a>
                  </div>

            </div>
  					<p class="overlay_p2"><a href="/art">Art</a></p>
  					<p class="overlay_p2"><a href="/#contact">Contact</a></p> 
    </div>
</div>

app/views/pages/commercial.html.erb
<%= render 'commercial' %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/press.html.erb
<%= render 'fancybox_script' %>



  <%= render 'press' %>